# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 999
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-name: 'searxng/searxng'
    versioning-strategy: "increase"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 999
    groups:
      artifacts:
        patterns:
          - 'actions/*-artifact'
      caches:
        patterns:
          - 'actions/cache'
          - 'actions/cache/*'
      sast:
        patterns:
          - 'github/codeql-*'
          - 'actions/dependency-review-action'
          - 'step-security/*'
          - 'microsoft/security-devops-action'
          - 'microsoft/DevSkim-Action'
          - 'ossf/*'
  - package-ecosystem: 'npm'
    directory: '/'
    registries: '*'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase
    open-pull-requests-limit: 999
    groups:
      hono:
        patterns:
          - 'hono'
          - '@hono/*'
      cloudflare:
        patterns:
          - 'cloudflare'
          - '@cloudflare/*'
          - 'wrangler'
        exclude-patterns:
          - '@cloudflare/workers-types'
      typescript-core:
        patterns:
          - 'typescript'
          - 'tsx'
      typescript-types:
        patterns:
          - '@types/*'
          - '@cloudflare/workers-types'
      code-management:
        patterns:
          - 'prettier'
          - 'prettier-plugin-*'
          - '@demosjarco/prettier-config'
          - 'eslint'
          - 'eslint-plugin-*'
          - '@microsoft/eslint-formatter-sarif'
          - '@eslint/*'
          - 'typescript-eslint'
